### PR TITLE
ForwardRef Support

### LINKED ISSUE #48: React 16.3+ forwardRef component
React 16.3+ [forwardRef()](https://reactjs.org/docs/forwarding-refs.html) will return a new component (type is `object`) that contains a `render` function and a `$$typeof` Symbol, and these should not be copied, otherwise may cause some bug

### Example to reproduce

```js
import React, { Component, createRef, forwardRef } from 'react';
import hoistStatics from 'hoist-non-react-statics';

function hoist(WrappedComponent) {
	return function createHoistedComponent(TargetComponent) {
		const HoistedComponent = forwardRef((props, ref) => (
			<TargetComponent {...props} forwardedRef={ref} />
		));

		if (WrappedComponent) {
			HoistedComponent.displayName = `hoisted(${WrappedComponent.displayName})`;
			hoistStatics(HoistedComponent, WrappedComponent /* , { render: true } */);
		}

		return HoistedComponent;
	};
}

function extraPropsHoc(extra) {
	return (WrappedComponent) => {
		@hoist(WrappedComponent)
		class Bar extends Component {
			render() {
				const { forwardedRef, ...props } = this.props;
				return <WrappedComponent {...props} {...extra} ref={forwardedRef} />;
			}
		}
		return Bar;
	};
}

@extraPropsHoc({ foo: 'foo' })
@extraPropsHoc({ bar: 'bar' })
class Foo extends Component {
	static displayName = 'Foo';

	log() {
		console.log('this.props', this.props);
	}

	render() {
		return <h1>Hello</h1>;
	}
}

export default class App extends Component {
	ref = createRef();

	componentDidMount() {
		this.ref.current.log();
	}

	render() {
		return <Foo ref={this.ref} />;
	}
}
```

### Result

this.props `{bar: "bar"}`

### Expect

this.props `{foo: "foo", bar: "bar"}`

If I uncomment `hoistStatics(HoistedComponent, WrappedComponent /* , { render: true } */)`, it will work as expected.

## Env

- react@16.3.2
- hoist-non-react-statics@2.5.0

### PR DESCRIPTION
**Pull request by mridgway**
Fixes #48. This adds support for ForwardRefs and provides a system for supporting new component types moving forward.

This will be a major version bump because it will only work with React 14+ due to the dependency on `react-is`.

This PR has been released as `3.0.0-rc.0` or tag `next` so that it can be tested with existing applications.

### CODE REVIEW

**Comment by benjaminbillet** [comment]
Hi, it seems to work fine (the statics are properly hoisted on my ref-forwarded component) but I got this warning when I mount the resulting component:

```
Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.
```

**Comment by mridgway** [comment]
@benjaminbillet I haven't been able to reproduce the warning you are seeing unless the component I am hoisting to is not a valid component also. Do you have an example repro case?

**Comment by mridgway** [comment]
I just found your repo and was able to reproduce. Fix incoming.

**Comment by mridgway** [comment]
There was a bug in detecting inheritance in plain objects that caused the function to hoist a lot of extra fields.

**Comment by oliviertassinari** [comment]
For the record, here is the cost of this feature:
[capture d ecran 2018-07-29 a 00 48 25](https://bundlephobia.com/result?p=hoist-non-react-statics@3.0.1)

**Comment by evocateur** [comment]
@oliviertassinari A bit misleading to only post a screenshot with the tooltip of the original size. The actual gzip size of 3.x is 1kb, easily justified by the increased functionality.

**Comment by eps1lon** [comment]
@mridgway Why is the peer to react >= 14 required? As far as I understood `react-is` it would just not recognize components from before v14. Since you currently only use `react-is` to detect types that were added in `16.3.0` this shouldn't be an issue.

**Pull request merged**
