### PR TITLE
Prepared build infrastructure, shipping es, cjs and umd formats

### PR DESCRIPTION
**Pull request by Andarist**
SIde note - I'm a little bit unsure why this is needed:
```js
var defineProperty = Object.defineProperty;
var getOwnPropertyNames = Object.getOwnPropertyNames;
var getOwnPropertySymbols = Object.getOwnPropertySymbols;
var getOwnPropertyDescriptor = Object.getOwnPropertyDescriptor;
var getPrototypeOf = Object.getPrototypeOf;
var objectPrototype = getPrototypeOf && getPrototypeOf(Object);
```

Are those property lookups considered costful so they are cached? By inlining them we could save 34 bytes (checked on minified and gzipped bundle)

### CODE REVIEW

**Comment by Andarist** [comment]
@mridgway friendly 🏓

**Comment by mridgway** [comment]
Thanks for doing this @Andarist. It looks great!

I'm going to take a closer look when I find some time to pull it down and play with the new build system.

**Comment by Andarist** [comment]
Thanks! If you need any help, or if you have any questions - just ping me :)

**Comment by mridgway** [comment]
Merged this manually with merge conflicts resolved to master. Thanks for doing this @Andarist!

**Pull request closed without merging**
